import Foundation

/// A conversation item emitted by or sent to the Realtime API.
public enum Item: Equatable, Hashable, Sendable {
	/// The lifecycle state of an item as reported by the server.
	public enum Status: String, Equatable, Hashable, Codable, Sendable {
		case completed
		case incomplete
		case inProgress = "in_progress"
	}

	/// Audio content paired with optional transcript text.
	public struct Audio: Equatable, Hashable, Codable, Sendable {
		public var audio: AudioData?
		public var transcript: String?

		public init(audio: AudioData? = nil, transcript: String? = nil) {
			self.audio = audio
			self.transcript = transcript
		}

		public init(audio: Data? = nil, transcript: String? = nil) {
			self.init(audio: audio.map(AudioData.init(data:)), transcript: transcript)
		}
	}

	/// A user, assistant, or system message in the conversation.
	public struct Message: Equatable, Hashable, Codable, Sendable {
		public enum Role: String, Equatable, Hashable, Codable, Sendable {
			case user
			case assistant
			case system
		}

		public struct InputImage: Equatable, Hashable, Codable, Sendable {
			public enum Detail: String, Equatable, Hashable, Codable, Sendable {
				case auto
				case low
				case high
				case original
			}

			public var detail: Detail?
			public var imageUrl: String

			public init(imageUrl: String, detail: Detail? = nil) {
				self.detail = detail
				self.imageUrl = imageUrl
			}
		}

		public enum Content: Equatable, Hashable, Sendable {
			case inputText(String)
			case inputAudio(Audio)
			case inputImage(InputImage)
			case outputText(String)
			case outputAudio(Audio)

			public var text: String? {
				switch self {
					case let .inputText(text): text
					case let .inputAudio(audio): audio.transcript
					case .inputImage: nil
					case let .outputText(text): text
					case let .outputAudio(audio): audio.transcript
				}
			}
		}

		public var content: [Content]
		public var id: String?
		public var object: String?
		public var role: Role
		public var status: Status

		public init(id: String? = nil, object: String? = nil, role: Role, status: Status = .completed, content: [Content]) {
			self.content = content
			self.id = id
			self.object = object
			self.role = role
			self.status = status
		}
	}

	/// A tool or function call item generated by the model.
	public struct FunctionCall: Equatable, Hashable, Codable, Sendable {
		public var arguments: String
		public var callId: String?
		public var id: String?
		public var name: String
		public var object: String?
		public var status: Status

		public init(id: String? = nil, object: String? = nil, status: Status = .completed, callId: String? = nil, name: String, arguments: String) {
			self.arguments = arguments
			self.callId = callId
			self.id = id
			self.name = name
			self.object = object
			self.status = status
		}
	}

	/// The output paired with a previously emitted function call.
	public struct FunctionCallOutput: Equatable, Hashable, Codable, Sendable {
		public var callId: String
		public var id: String?
		public var object: String?
		public var output: String
		public var status: Status

		public init(id: String? = nil, object: String? = nil, status: Status = .completed, callId: String, output: String) {
			self.callId = callId
			self.id = id
			self.object = object
			self.output = output
			self.status = status
		}
	}

	public struct MCPCall: Equatable, Hashable, Codable, Sendable {
		public struct Error: Equatable, Hashable, Codable, Sendable {
			public var code: Int?
			public var message: String
			public var type: String

			public init(code: Int? = nil, message: String, type: String) {
				self.code = code
				self.message = message
				self.type = type
			}
		}

		public var approvalRequestId: String?
		public var arguments: String
		public var error: Error?
		public var id: String
		public var name: String
		public var object: String?
		public var output: String?
		public var serverLabel: String
		public var status: Status?

		public init(
			id: String,
			object: String? = nil,
			status: Status? = nil,
			serverLabel: String,
			name: String,
			arguments: String,
			output: String? = nil,
			error: Error? = nil,
			approvalRequestId: String? = nil
		) {
			self.approvalRequestId = approvalRequestId
			self.arguments = arguments
			self.error = error
			self.id = id
			self.name = name
			self.object = object
			self.output = output
			self.serverLabel = serverLabel
			self.status = status
		}
	}

	public struct MCPApprovalRequest: Equatable, Hashable, Codable, Sendable {
		public var arguments: String
		public var id: String
		public var name: String
		public var object: String?
		public var serverLabel: String
		public var status: Status?

		public init(id: String, object: String? = nil, status: Status? = nil, serverLabel: String, name: String, arguments: String) {
			self.arguments = arguments
			self.id = id
			self.name = name
			self.object = object
			self.serverLabel = serverLabel
			self.status = status
		}
	}

	public struct MCPApprovalResponse: Equatable, Hashable, Codable, Sendable {
		public var approvalRequestId: String
		public var approve: Bool
		public var id: String
		public var object: String?
		public var reason: String?
		public var status: Status?

		public init(id: String, object: String? = nil, status: Status? = nil, approvalRequestId: String, approve: Bool, reason: String? = nil) {
			self.approvalRequestId = approvalRequestId
			self.approve = approve
			self.id = id
			self.object = object
			self.reason = reason
			self.status = status
		}
	}

	public struct MCPListTools: Equatable, Hashable, Codable, Sendable {
		public struct Tool: Equatable, Hashable, Codable, Sendable {
			public struct Annotations: Equatable, Hashable, Codable, Sendable {
				public var destructiveHint: Bool?
				public var idempotentHint: Bool?
				public var openWorldHint: Bool?
				public var readOnlyHint: Bool?
				public var title: String?

				public init(
					destructiveHint: Bool? = nil,
					idempotentHint: Bool? = nil,
					openWorldHint: Bool? = nil,
					readOnlyHint: Bool? = nil,
					title: String? = nil
				) {
					self.destructiveHint = destructiveHint
					self.idempotentHint = idempotentHint
					self.openWorldHint = openWorldHint
					self.readOnlyHint = readOnlyHint
					self.title = title
				}
			}

			public var annotations: Annotations?
			public var description: String?
				public var inputSchema: GenerationSchema
				public var name: String

				public init(name: String, description: String? = nil, inputSchema: GenerationSchema, annotations: Annotations? = nil) {
					self.annotations = annotations
					self.description = description
					self.inputSchema = inputSchema
				self.name = name
			}
		}

		public var id: String?
		public var object: String?
		public var serverLabel: String
		public var status: Status?
		public var tools: [Tool]

		public init(id: String? = nil, object: String? = nil, status: Status? = nil, serverLabel: String, tools: [Tool]) {
			self.id = id
			self.object = object
			self.serverLabel = serverLabel
			self.status = status
			self.tools = tools
		}
	}

	case message(Message)
	case functionCall(FunctionCall)
	case functionCallOutput(FunctionCallOutput)
	case mcpCall(MCPCall)
	case mcpApprovalRequest(MCPApprovalRequest)
	case mcpApprovalResponse(MCPApprovalResponse)
	case mcpListTools(MCPListTools)

	public var id: String? {
		switch self {
			case let .message(message): message.id
			case let .functionCall(functionCall): functionCall.id
			case let .functionCallOutput(functionCallOutput): functionCallOutput.id
			case let .mcpCall(mcpCall): mcpCall.id
			case let .mcpApprovalRequest(request): request.id
			case let .mcpApprovalResponse(response): response.id
			case let .mcpListTools(list): list.id
		}
	}
}

extension Item: Codable {
	private enum CodingKeys: String, CodingKey {
		case type
	}

	public init(from decoder: any Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		let type = try container.decode(String.self, forKey: .type)

		switch type {
			case "message":
				self = .message(try Message(from: decoder))
			case "function_call":
				self = .functionCall(try FunctionCall(from: decoder))
			case "function_call_output":
				self = .functionCallOutput(try FunctionCallOutput(from: decoder))
			case "mcp_call":
				self = .mcpCall(try MCPCall(from: decoder))
			case "mcp_approval_request":
				self = .mcpApprovalRequest(try MCPApprovalRequest(from: decoder))
			case "mcp_approval_response":
				self = .mcpApprovalResponse(try MCPApprovalResponse(from: decoder))
			case "mcp_list_tools":
				self = .mcpListTools(try MCPListTools(from: decoder))
			default:
				throw DecodingError.dataCorruptedError(forKey: .type, in: container, debugDescription: "Unknown item type: \(type)")
		}
	}

	public func encode(to encoder: any Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)

		switch self {
			case let .message(message):
				try container.encode("message", forKey: .type)
				try message.encode(to: encoder)
			case let .functionCall(functionCall):
				try container.encode("function_call", forKey: .type)
				try functionCall.encode(to: encoder)
			case let .functionCallOutput(functionCallOutput):
				try container.encode("function_call_output", forKey: .type)
				try functionCallOutput.encode(to: encoder)
			case let .mcpCall(mcpCall):
				try container.encode("mcp_call", forKey: .type)
				try mcpCall.encode(to: encoder)
			case let .mcpApprovalRequest(request):
				try container.encode("mcp_approval_request", forKey: .type)
				try request.encode(to: encoder)
			case let .mcpApprovalResponse(response):
				try container.encode("mcp_approval_response", forKey: .type)
				try response.encode(to: encoder)
			case let .mcpListTools(list):
				try container.encode("mcp_list_tools", forKey: .type)
				try list.encode(to: encoder)
		}
	}
}

extension Item.Message.Content: Codable {
	private enum CodingKeys: String, CodingKey {
		case audio
		case detail
		case imageUrl
		case text
		case transcript
		case type
	}

	public init(from decoder: any Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		let type = try container.decode(String.self, forKey: .type)

		switch type {
			case "input_text":
				self = .inputText(try container.decode(String.self, forKey: .text))
			case "input_audio":
				self = .inputAudio(try Item.Audio(from: decoder))
			case "input_image":
				self = .inputImage(.init(
					imageUrl: try container.decode(String.self, forKey: .imageUrl),
					detail: try container.decodeIfPresent(Item.Message.InputImage.Detail.self, forKey: .detail)
				))
			case "output_text":
				self = .outputText(try container.decode(String.self, forKey: .text))
			case "output_audio":
				self = .outputAudio(try Item.Audio(from: decoder))
			default:
				throw DecodingError.dataCorruptedError(forKey: .type, in: container, debugDescription: "Unknown message content type: \(type)")
		}
	}

	public func encode(to encoder: any Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)

		switch self {
			case let .inputText(text):
				try container.encode("input_text", forKey: .type)
				try container.encode(text, forKey: .text)
			case let .inputAudio(audio):
				try container.encode("input_audio", forKey: .type)
				try container.encode(audio.audio, forKey: .audio)
				try container.encodeIfPresent(audio.transcript, forKey: .transcript)
			case let .inputImage(image):
				try container.encode("input_image", forKey: .type)
				try container.encode(image.imageUrl, forKey: .imageUrl)
				try container.encodeIfPresent(image.detail, forKey: .detail)
			case let .outputText(text):
				try container.encode("output_text", forKey: .type)
				try container.encode(text, forKey: .text)
			case let .outputAudio(audio):
				try container.encode("output_audio", forKey: .type)
				try container.encode(audio.audio, forKey: .audio)
				try container.encodeIfPresent(audio.transcript, forKey: .transcript)
		}
	}
}
