import Foundation

/// Configures the model’s response behavior inside the session DSL.
public struct Response: SessionComponentConvertible {
	public struct IncludeDirective {
		fileprivate let values: [SessionConfiguration.Include]

		private init(_ values: [SessionConfiguration.Include]) {
			self.values = values
		}

		public static func field(_ value: SessionConfiguration.Include) -> Self {
			.init([value])
		}
	}

	private let modality: SessionConfiguration.OutputModality
	private let maxTokens: SessionConfiguration.MaxOutputTokens?
	private let truncation: SessionConfiguration.Truncation?
	private var includes: [SessionConfiguration.Include]
	private let validationErrors: [SessionConfigurationBuilderError]

	public init(_ modality: SessionConfiguration.OutputModality, @ResponseBuilder _ content: () -> [ResponseComponent] = { [] }) {
		var draft = ResponseDraft()
		let components = content()

		for component in components {
			component.apply(&draft)
		}

		self.modality = modality
		self.maxTokens = draft.maxTokens
		self.truncation = draft.truncation
		self.includes = []
		self.validationErrors = components.flatMap(\.validationErrors)
	}

	public func include(_ directive: IncludeDirective) -> Self {
		var copy = self
		copy.includes.append(contentsOf: directive.values)
		return copy
	}

	public var sessionComponent: SessionComponent {
		SessionComponent({ draft in
			draft.outputModalities = [modality]
			draft.maxOutputTokens = maxTokens
			draft.truncation = truncation
			draft.include.append(contentsOf: includes)
		}, validationErrors: validationErrors)
	}
}

public struct ResponseComponent {
	fileprivate let apply: (inout ResponseDraft) -> Void
	fileprivate let validationErrors: [SessionConfigurationBuilderError]

	fileprivate init(_ apply: @escaping (inout ResponseDraft) -> Void, validationErrors: [SessionConfigurationBuilderError] = []) {
		self.apply = apply
		self.validationErrors = validationErrors
	}
}

public protocol ResponseComponentConvertible {
	var responseComponent: ResponseComponent { get }
}

@resultBuilder
public enum ResponseBuilder {
	public static func buildExpression<T: ResponseComponentConvertible>(_ expression: T) -> [ResponseComponent] {
		[expression.responseComponent]
	}

	public static func buildBlock(_ components: [ResponseComponent]...) -> [ResponseComponent] {
		components.flatMap(\.self)
	}
}

/// Sets the maximum token budget for a response generated by the DSL.
public struct MaxTokens: ResponseComponentConvertible {
	public enum Value: Sendable {
		case max
	}

	private let value: SessionConfiguration.MaxOutputTokens?
	private let validationErrors: [SessionConfigurationBuilderError]

	public init(_ value: Value) {
		switch value {
			case .max:
				self.value = .inf
		}
		self.validationErrors = []
	}

	@_disfavoredOverload
	public init(_ value: Int) {
		if (1...4096).contains(value) {
			self.value = .limited(value)
			self.validationErrors = []
		} else {
			self.value = nil
			self.validationErrors = [.invalidMaxTokens(value)]
		}
	}

	public var responseComponent: ResponseComponent {
		ResponseComponent({ draft in
			draft.maxTokens = value
		}, validationErrors: validationErrors)
	}
}

/// Sets the truncation policy for responses generated by the DSL.
public struct Truncation: ResponseComponentConvertible {
	private let value: SessionConfiguration.Truncation

	public init(_ value: SessionConfiguration.Truncation) {
		self.value = value
	}

	public var responseComponent: ResponseComponent {
		ResponseComponent { draft in
			draft.truncation = value
		}
	}
}

private struct ResponseDraft {
	var maxTokens: SessionConfiguration.MaxOutputTokens?
	var truncation: SessionConfiguration.Truncation?
}
